AV-192673 Upgrade gateway-api version to v1.0.0
vmware/load-balancer-and-ingress-services-for-kubernetes pull request #1330
Opened 2023-11-23 09:04 UTC by aaha97

included in the PR:
- moving from gatewayv1beta1 to gatewayv1
- upgrade go version from 1.20 to 1.21
- upgraded k8s api version to v0.28.3 - added fixes to ako code for LoadBalancerIngress status
- fixes to statefulset.yaml for nodePort support with gatewayAPI

2023-11-28 09:49 UTC, aaha97 commented
build ako

2023-11-29 04:40 UTC, aaha97 commented
build ako

2023-11-29 05:08 UTC, akshayhavile commented
build ako

2023-11-29 06:44 UTC, akshayhavile reviewed
@aaha97: Should we take care of removing `v1alpha1` from codebase? or will that be a separate PR?

2023-11-29 06:50 UTC, aaha97 commented on ako-operator/main.go
> +		Scheme: scheme,
yes, namespace is not a field anymore

2023-11-29 06:55 UTC, aaha97 commented on internal/status/ing_status.go
> +func compareLBStatus(oldStatus, newStatus *corev1.LoadBalancerStatus) (bool, sets.Set[string], sets.Set[string]) {
this is not a functional change. since IngressLoadBalancerStatus was added to networking/v1 the name had to be changed. I have only run the UTs

2023-11-29 07:02 UTC, aaha97 commented
> @aaha97: Should we take care of removing `v1alpha1` from codebase? or will that be a separate PR?

we will take that up as a separate PR

2023-12-04 03:17 UTC, arihantg approved these changes
LGTM

2023-12-04 10:18 UTC, pkoshtavmware requested changes

2023-12-07 09:05 UTC, aaha97 commented
build ako

2023-12-07 09:18 UTC, aaha97 commented
build ako

2023-12-07 09:20 UTC, aaha97 commented
build ako

2023-12-07 09:25 UTC, aaha97 commented
build ako

2023-12-07 09:28 UTC, aaha97 commented on go.mod
> +	k8s.io/api => k8s.io/api v0.28.3
cleaned up go.mod

2023-12-07 09:28 UTC, aaha97 commented on go.sum
> +cloud.google.com/go v0.34.0/go.mod h1:aQUYkXzVsufM+DwF1aE+0xfcU+56JwCaLick0ClmMTw=
i have run `go mod tidy` and `go mod vendor`

2023-12-07 09:42 UTC, akshayhavile commented
build ako

2023-12-11 06:13 UTC, akshayhavile approved these changes
LGTM

2023-12-11 11:56 UTC, pkoshtavmware approved these changes
LGTM

2023-12-12 14:44 UTC, merged