AV-206829 move gateway/route status updates to status layer
vmware/load-balancer-and-ingress-services-for-kubernetes pull request #1549
Opened 2024-10-03 11:53 UTC by arihantg

2024-10-04 06:41 UTC, pkoshtavmware approved these changes
LGTM

2024-10-06 14:33 UTC, akshayhavile requested changes
@arihantg @pkoshtavmware All Record call are blocking calls. We should utilise the enqueue and dequeue functionality of status queue as we do when VS gets created and we enqueue status option.

2024-10-07 06:11 UTC, arihantg commented
> @arihantg @pkoshtavmware All Record call are blocking calls. We should utilise the enqueue and dequeue functionality of status queue as we do when VS gets created and we enqueue status option.

@akshayhavile PublishToStatusQueue is added in Record which is doing the enqueue operation

2024-10-07 06:27 UTC, akshayhavile approved these changes

2024-10-07 06:27 UTC, merged