change version of ingressclass to networking/v1beta1 in indexer
vmware/load-balancer-and-ingress-services-for-kubernetes pull request #641
Opened 2021-09-30 18:20 UTC by monotosh-avi

This is done to make it consistent with ingressclass version when it is fetched through the indexer
Fixes AV-126133

2021-09-30 18:29 UTC, sudswasavi approved these changes

2021-09-30 18:41 UTC, sudswasavi commented
build ako

2021-09-30 18:43 UTC, sudswasavi commented
build ako

2021-09-30 18:44 UTC, sudswasavi commented
build ako

2021-09-30 18:54 UTC, sudswasavi commented
build ako

2021-09-30 19:12 UTC, chauhanshubham requested changes
we have the same code in `controller.go` (https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blob/357767063214164df92e6cf93a2ebf0b3e30c6cb/internal/k8s/controller.go#L983) which is the correct version of it. that's what seemed to have caused the confusion :)

2021-10-01 04:11 UTC, chauhanshubham approved these changes
thanks

2021-10-01 04:46 UTC, monotosh-avi commented
build ako

2021-10-01 05:11 UTC, monotosh-avi commented
build ako

2021-10-01 05:44 UTC, sudswasavi commented
build ako

2021-10-01 06:29 UTC, merged