Change network profile based on license
vmware/load-balancer-and-ingress-services-for-kubernetes pull request #782
Opened 2022-02-21 08:08 UTC by metalcyanide

2022-03-01 04:47 UTC, chauhanshubham requested changes
I think a better way is to make this API call during bootup and store the configured license on the control_config.go's `akoControlConfig` struct globally. Making API calls in the graph layer queue will slow down AKO a lot, and it is totally unnecessary to make this call everytime we create the node.

2022-04-07 06:13 UTC, chauhanshubham commented
LGTM, could you please run `make golangci-fix` and push again? there are some lint issues. Thanks

2022-04-07 08:14 UTC, akshayhavile commented on internal/lib/control_config.go
> +		utils.AviLog.Warnf("Unable to fetch system configuration, error %s", err.Error())
@metalcyanide : Should we return from here in case of error? Else we might get error at line number 266

2022-04-25 04:41 UTC, swathinsankaran requested changes

2022-04-25 04:41 UTC, swathinsankaran commented on internal/rest/rest_utils.go
> +func GetLicenseTypeFromURI() (models.SystemConfiguration, error) {
lib/control_config.go also has the same function.

2022-04-25 04:41 UTC, swathinsankaran commented on internal/lib/control_config.go
> +func GetLicenseTypeFromURI(client *clients.AviClient) (models.SystemConfiguration, error) {
please take care of the name of the function as the function's name and what the function actually returns are not the same.

2022-04-25 04:41 UTC, swathinsankaran commented on pkg/utils/avi_rest_utils.go
> +func LicenseTypeFromURI() (models.SystemConfiguration, error) {
function name and what function actually returns are different here.

2022-04-25 07:35 UTC, metalcyanide commented
build ako

2022-04-25 08:46 UTC, metalcyanide commented
build ako

2022-04-25 20:43 UTC, metalcyanide commented
build ako

2022-04-26 08:36 UTC, metalcyanide commented
build ako

2022-04-26 08:37 UTC, metalcyanide commented
build ako

2022-04-26 09:16 UTC, metalcyanide commented
build ako

2022-04-27 06:23 UTC, akshayhavile approved these changes
LGTM

2022-04-27 08:24 UTC, metalcyanide commented
build ako

2022-04-27 09:33 UTC, metalcyanide commented
build ako

2022-04-27 10:39 UTC, metalcyanide commented
build ako

2022-04-27 11:55 UTC, metalcyanide commented
build ako

2022-04-28 10:11 UTC, chauhanshubham commented
build ako

2022-04-28 11:21 UTC, chauhanshubham approved these changes

2022-04-28 11:23 UTC, swathinsankaran approved these changes

2022-04-28 11:23 UTC, merged